search : main.o getContent.o dfs.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o HtmlParser.o itoa.o store.o getdft.o main.cpp getContent.cpp dfs.cpp getcontent.cpp get_title.cpp get_text.cpp get_url.cpp get_in_a_certain_way.cpp HtmlParser.cpp itoa.cpp store.cpp getdft.cpp
	g++ -o search main.o getContent.o dfs.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o HtmlParser.o itoa.o store.o getdft.o
main.o : main.cpp head.h 
	g++ -c main.cpp
dfs.o : dfs.cpp head.h
	g++ -c dfs.cpp
getContent.o : getContent.cpp head.h
	g++ -c getContent.cpp
getcontent.o : getcontent.cpp head.h
	g++ -c getcontent.cpp
get_title.o : get_title.cpp head.h
	g++ -c get_title.cpp
get_text.o : get_text.cpp head.h
	g++ -c get_text.cpp
get_url.o : get_url.cpp head.h
	g++ -c get_url.cpp
get_in_a_certain_way.o : get_in_a_certain_way.cpp head.h
	g++ -c get_in_a_certain_way.cpp
HtmlParser.o : HtmlParser.cpp head.h
	g++ -c HtmlParser.cpp
itoa.o : itoa.cpp head.h 
	g++ -c itoa.cpp
store.o : store.cpp head.h 
	g++ -c store.cpp
getdft.o :getdft.cpp head.h
	g++ -c getdft.cpp