SE : main.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o analysis.o itoa.o similarity.o store.o storecommonword.o main.cpp getcontent.cpp get_title.cpp get_text.cpp get_url.cpp get_in_a_certain_way.cpp analysis.cpp itoa.cpp similarity.cpp store.cpp storecommonword.cpp
	g++ -o SE main.o getcontent.o get_title.o get_text.o get_url.o get_in_a_certain_way.o analysis.o itoa.o similarity.o store.o storecommonword.o -std=c++11
main.o : main.cpp head.h
	g++ -c main.cpp
getcontent.o : getcontent.cpp head.h
	g++ -c getcontent.cpp
get_title.o : get_title.cpp head.h
	g++ -c get_title.cpp
get_text.o : get_text.cpp head.h
	g++ -c get_text.cpp
get_url.o : get_url.cpp head.h
	g++ -c get_url.cpp
get_in_a_certain_way.o : get_in_a_certain_way.cpp head.h
	g++ -c get_in_a_certain_way.cpp
analysis.o :analysis.cpp head.h
	g++ -c analysis.cpp
itoa.o : itoa.cpp head.h
	g++ -c itoa.cpp
similarity.o : similarity.cpp head.h
	g++ -c similarity.cpp 
store.o  : store.cpp head.h
	g++ -c store.cpp
storecommonword.o :storecommonword.cpp head.h
	g++ -c storecommonword.cpp

