bighomework : main.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o main.cpp getcontent.cpp get_title.cpp get_text.cpp get_url.cpp get_in_a_certain_way.cpp
	g++ -o bighomework main.o getcontent.o get_title.o get_text.o get_url.o get_in_a_certain_way.o -std=c++11
main.o : main.cpp parser.h
	g++ -c main.cpp
getcontent.o : getcontent.cpp parser.h
	g++ -c getcontent.cpp
get_title.o : get_title.cpp parser.h
	g++ -c get_title.cpp
get_text.o : get_text.cpp parser.h
	g++ -c get_text.cpp
get_url.o : get_url.cpp parser.h
	g++ -c get_url.cpp
get_in_a_certain_way.o : get_in_a_certain_way.cpp parser.h
	g++ -c get_in_a_certain_way.cpp




