bighomework : main.o getcontent.o dfs.o datechange.o dealwith.o main.cpp getcontent.cpp dfs.cpp datechange.cpp dealwith.cpp
	g++ -o bighomework main.o getcontent.o dfs.o datechange.o dealwith.o -std=c++11
main.o : main.cpp head.h
	g++ -c main.cpp
dfs.o : dfs.cpp head.h
	g++ -c dfs.cpp
datechange.o : datechange.cpp head.h 
	g++ -c datechange.cpp
getcontent.o : getcontent.cpp head.h
	g++ -c getcontent.cpp
dealwith.o : dealwith.cpp head.h 
	g++ -c dealwith.cpp