aBigInteger:main.o BigInteger.o
	g++ main.o BigInteger.o -o aBigInteger.o
main.o:main.cpp BigInteger.h
	g++ -c main.cpp -o main.o
crawler.o:crawler.cpp crawler.h
	g++ -c BigInteger.cpp -o BigInteger.o
