bighomework : main.o getContent.o dfs.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o crawled_parser.o parser.o main.cpp getContent.cpp dfs.cpp getcontent.cpp get_title.cpp get_text.cpp get_url.cpp get_in_a_certain_way.cpp crawled_parser.cpp parser.cpp
	g++ -o bighomework main.o getContent.o dfs.o getcontent.o  get_title.o get_text.o get_url.o get_in_a_certain_way.o crawled_parser.o parser.o -std=c++11
main.o : main.cpp head.h 
	g++ -c main.cpp
dfs.o : dfs.cpp head.h
	g++ -c dfs.cpp
getContent.o : getContent.cpp head.h
	g++ -c getContent.cpp
getcontent.o : getcontent.cpp head.h
	g++ -c getcontent.cpp
get_title.o : get_title.cpp head.h
	g++ -c get_title.cpp
get_text.o : get_text.cpp head.h
	g++ -c get_text.cpp
get_url.o : get_url.cpp head.h
	g++ -c get_url.cpp
get_in_a_certain_way.o : get_in_a_certain_way.cpp head.h
	g++ -c get_in_a_certain_way.cpp
crawled_parser.o: crawled_parser.cpp head.h
	g++ -c crawled_parser.cpp
parser.o : parser.cpp head.h
	g++ -c parser.cpp
