search_engine : main.cpp search.h search_engine.o
	g++ -o search_engine main.cpp search_engine.o
search_engine.o : search_engine.cpp
	g++ -c search_engine.cpp
clean :
	rm -rf search_engine.o search_engine
